services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - CONTEXT=development
      - PORT=3001
    command: sh -c "yarn start --host 0.0.0.0"
volumes:
  node_modules:
