module.exports = {
  docs: [
    {
      id: "introduction",
      type: "doc",
    },
    {
      id: "quick-start",
      type: "doc",
      customProps: { tag: "Popular" },
    },
    {
      id: "why-questdb",
      type: "doc",
      customProps: { tag: "Popular" },
    },
    {
      id: "guides/schema-design-essentials",
      type: "doc",
      customProps: { tag: "Popular" },
    },
    {
      id: "guides/influxdb-migration",
      type: "doc",
      customProps: { tag: "Popular" },
    },
    {
      type: "category",
      label: "Ingestion Reference",
      items: [
        {
          id: "ingestion-overview",
          type: "doc",
          label: "Overview",
        },
        {
          type: "category",
          label: "Language Clients",
          collapsed: false,
          items: [
            {
              id: "configuration-string",
              type: "doc",
              label: "Configuration string",
            },
            {
              id: "clients/ingest-python",
              type: "doc",
              label: "Python",
            },
            {
              id: "clients/ingest-go",
              type: "doc",
              label: "Go",
            },
            {
              id: "clients/java_ilp",
              type: "doc",
              label: "Java",
            },
            {
              id: "clients/ingest-rust",
              type: "doc",
              label: "Rust",
            },
            {
              id: "clients/ingest-node",
              type: "doc",
              label: "Node.js",
            },
            {
              id: "clients/ingest-c-and-cpp",
              type: "doc",
              label: "C & C++",
            },
            {
              id: "clients/ingest-dotnet",
              type: "doc",
              label: ".NET",
            },
            {
              id: "clients/date-to-timestamp-conversion",
              type: "doc",
              label: "Date to Timestamp Conversion",
            },
          ],
        },
        {
          type: "category",
          label: "Message Brokers",
          collapsed: false,
          items: [
            "third-party-tools/kafka",
            "third-party-tools/telegraf",
            "third-party-tools/redpanda",
            "third-party-tools/flink",
          ],
        },
        {
          type: "category",
          label: "Protocols",
          items: [
            {
              type: "category",
              label: "InfluxDB Line Protocol (ILP)",
              items: [
                "reference/api/ilp/overview",
                "reference/api/ilp/advanced-settings",
                "reference/api/ilp/columnset-types",
              ],
            },
            "reference/api/postgres",
            "reference/api/rest",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Query & SQL Reference",
      items: [
        "reference/sql/overview",
        {
          type: "category",
          label: "PGWire Clients",
          collapsed: false,
          items: [
             "pgwire/pgwire-intro",
            {
              id: "pgwire/python",
              type: "doc",
              label: "Python",
            },
            {
              id: "pgwire/rust",
              type: "doc",
              label: "Rust",
            },
            {
              id: "pgwire/javascript",
              type: "doc",
              label: "Node.js",
            },
            {
              id: "pgwire/java",
              type: "doc",
              label: "Java",
            },
            {
              id: "pgwire/c-sharp",
              type: "doc",
              label: ".NET",
            },
            {
              id: "pgwire/go",
              type: "doc",
              label: "Go",
            },
            {
              id: "pgwire/php",
              type: "doc",
              label: "PHP",
            },
            {
              id: "pgwire/rpostgres",
              type: "doc",
              label: "R",
            },
          ]
        },
        "reference/sql/datatypes",
        "concept/sql-execution-order",
        {
          type: "category",
          label: "SQL Syntax",
          items: [
            {
              id: "reference/sql/acl/add-user",
              type: "doc",
              customProps: { tag: "Enterprise" },
            },
            {
              type: "category",
              label: "ALTER",
              items: [
                {
                  type: "category",
                  label: "ALTER COLUMN",
                  items: [
                    "reference/sql/alter-table-alter-column-add-index",
                    "reference/sql/alter-table-alter-column-cache",
                    "reference/sql/alter-table-alter-column-drop-index",
                    "reference/sql/alter-table-change-column-type",
                    "reference/sql/alter-table-change-symbol-capacity",
                  ],
                },
                {
                  id: "reference/sql/acl/alter-service-account",
                  type: "doc",
                  customProps: { tag: "Enterprise" },
                },
                {
                  type: "category",
                  label: "ALTER TABLE",
                  items: [
                    "reference/sql/alter-table-add-column",
                    "reference/sql/alter-table-attach-partition",
                    "reference/sql/alter-table-change-column-type",
                    "reference/sql/alter-table-change-symbol-capacity",
                    "reference/sql/alter-table-detach-partition",
                    "reference/sql/alter-table-disable-deduplication",
                    "reference/sql/alter-table-drop-column",
                    "reference/sql/alter-table-drop-partition",
                    "reference/sql/alter-table-enable-deduplication",
                    "reference/sql/alter-table-rename-column",
                    "reference/sql/alter-table-resume-wal",
                    "reference/sql/alter-table-set-param",
                    "reference/sql/alter-table-set-type",
                    "reference/sql/alter-table-set-ttl",
                    "reference/sql/alter-table-squash-partitions",
                  ],
                },
                {
                  type: "category",
                  label: "ALTER MATERIALIZED VIEW",
                  items: [
                    "reference/sql/alter-mat-view-change-symbol-capacity",
                    "reference/sql/alter-mat-view-set-refresh-limit",
                    "reference/sql/alter-mat-view-set-ttl",
                    "reference/sql/alter-mat-view-resume-wal",
                  ],
                },
                {
                  id: "reference/sql/acl/alter-user",
                  type: "doc",
                  customProps: { tag: "Enterprise" },
                },
              ],
            },
            {
              id: "reference/sql/acl/assume-service-account",
              type: "doc",
              customProps: { tag: "Enterprise" },
            },
            "reference/sql/cancel-query",
            "reference/sql/checkpoint",
            "reference/sql/copy",
            {
              type: "category",
              label: "CREATE",
              items: [
                  "reference/sql/create-table",
                  {
                    id: "reference/sql/acl/create-group",
                    type: "doc",
                    customProps: { tag: "Enterprise" },
                  },
                  "reference/sql/create-mat-view",
                  {
                    id: "reference/sql/acl/create-service-account",
                    type: "doc",
                    customProps: { tag: "Enterprise" },
                  },
                  {
                    id: "reference/sql/acl/create-user",
                    type: "doc",
                    customProps: { tag: "Enterprise" },
                  }
              ]
            },
            {
              type: "category",
              label: "DROP",
              items: [
                      "reference/sql/drop",
                      {
                        id: "reference/sql/acl/drop-group",
                        type: "doc",
                        customProps: { tag: "Enterprise" },
                      },
                      "reference/sql/drop-mat-view",
                      {
                        id: "reference/sql/acl/drop-service-account",
                        type: "doc",
                        customProps: { tag: "Enterprise" },
                      },
                      {
                        id: "reference/sql/acl/drop-user",
                        type: "doc",
                        customProps: { tag: "Enterprise" },
                      },
              ]
            },
            "reference/sql/explain",
            {
              id: "reference/sql/acl/exit-service-account",
              type: "doc",
              customProps: { tag: "Enterprise" },
            },
            {
              type: "category",
              label: "GRANT",
              items: [
                      {
                        id: "reference/sql/acl/grant",
                        type: "doc",
                        customProps: { tag: "Enterprise" },
                      },
                      {
                        id: "reference/sql/acl/grant-assume-service-account",
                        type: "doc",
                        customProps: { tag: "Enterprise" },
                      },
              ]
            },
            "reference/sql/insert",
            "reference/sql/refresh-mat-view",
            "reference/sql/reindex",
            "reference/sql/rename",
            {
              id: "reference/sql/acl/remove-user",
              type: "doc",
              customProps: { tag: "Enterprise" },
            },
            {
              type: "category",
              label: "REVOKE",
              items: [
                      {
                        id: "reference/sql/acl/revoke",
                        type: "doc",
                        customProps: { tag: "Enterprise" },
                      },
                      {
                        id: "reference/sql/acl/revoke-assume-service-account",
                        type: "doc",
                        customProps: { tag: "Enterprise" },
                      },
              ]
            },
            {
              type: "category",
              label: "SELECT",
              items: [
                "reference/sql/select",
                "reference/sql/asof-join",
                "reference/sql/case",
                "reference/sql/cast",
                "reference/sql/declare",
                "reference/sql/distinct",
                "reference/sql/fill",
                "reference/sql/group-by",
                "reference/sql/join",
                "reference/sql/latest-on",
                "reference/sql/limit",
                "reference/sql/order-by",
                "reference/sql/over",
                "reference/sql/sample-by",
                "reference/sql/where",
                "reference/sql/with",
              ],
            },
            "reference/sql/show",
            "reference/sql/snapshot",
            "reference/sql/truncate",
            "reference/sql/union-except-intersect",
            "reference/sql/update",
            "reference/sql/vacuum-table",
          ],
        },
        {
          type: "category",
          label: "Functions",
          items: [
            "reference/function/aggregation",
            "reference/function/binary",
            "reference/function/boolean",
            "reference/function/conditional",
            "reference/function/date-time",
            "reference/function/finance",
            "reference/function/hash",
            "reference/function/json",
            "reference/function/meta",
            "reference/function/numeric",
            "reference/function/parquet",
            "reference/function/pattern-matching",
            "reference/function/random-value-generator",
            "reference/function/row-generator",
            "reference/function/spatial",
            "reference/function/text",
            "reference/function/timestamp-generator",
            "reference/function/timestamp",
            "reference/function/touch",
            "reference/function/trigonometric",
            "reference/function/uuid",
            "reference/function/window",
          ],
        },
        {
          type: "category",
          label: "Operators",
          items: [
            "reference/operators/bitwise",
            "reference/operators/comparison",
            "reference/operators/date-time",
            "reference/operators/ipv4",
            "reference/operators/logical",
            "reference/operators/misc",
            "reference/operators/numeric",
            "reference/operators/precedence",
            "reference/operators/spatial",
            "reference/operators/text",
          ],
        },
      ],
    },
    {
      label: "Deployment",
      type: "category",
      items: [
        "deployment/docker",
        "deployment/kubernetes",
        "deployment/systemd",
        "deployment/aws",
        "deployment/azure",
        "deployment/gcp",
        "deployment/digital-ocean",
      ],
    },
    {
      label: "Operations",
      type: "category",
      items: [
        "operations/capacity-planning",
        {
          id: "configuration",
          type: "doc",
        },
        "operations/command-line-options",
        "operations/backup",
        {
          label: "Authentication",
          type: "category",
          collapsed: false,
          items: [
            {
              id: "operations/rbac",
              type: "doc",
              label: "Role-Based Access Control (RBAC)",
              customProps: { tag: "Enterprise" },
            },
            {
              id: "operations/openid-connect-oidc-integration",
              type: "doc",
              label: "OpenID Connect (OIDC)",
              customProps: { tag: "Enterprise" },
            },
            {
              type: "doc",
              id: "operations/tls",
              customProps: { tag: "Enterprise" },
            },
          ]
        },
        "operations/logging-metrics",
        "operations/data-retention",
        "operations/design-for-performance",
        "operations/updating-data",
        "operations/task-automation",
        {
          type: "doc",
          id: "operations/replication",
          customProps: { tag: "Enterprise" },
        },
        {
          id: "operations/multi-primary-ingestion",
          type: "doc",
          label: "Multi-primary ingestion",
          customProps: { tag: "Enterprise" },
        },
      ],
    },
    {
      label: "Guides & Tutorials",
      type: "category",
      items: [
        {
          id: "guides/microsoft-entraid-oidc",
          label: "Active Directory - Microsoft Entra ID",
          type: "doc",
          customProps: { tag: "Enterprise" },
        },
        {
          id: "guides/active-directory-pingfederate",
          label: "Active Directory - PingFederate",
          type: "doc",
          customProps: { tag: "Enterprise" },
        },
        "guides/create-database",
        {
          id: "guides/enterprise-quick-start",
          type: "doc",
          customProps: { tag: "Enterprise" },
        },
        "guides/compression-zfs",
        "reference/api/java-embedded",
        "guides/import-csv",
        "guides/mat-views",
        "guides/modifying-data",
        "guides/replication-tuning",
        "guides/working-with-timestamps-timezones",
        "web-console",
        {
          label: "Blog tutorials 🔗",
          type: "link",
          href: "https://questdb.com/blog/?tag=tutorial",
        },
      ],
    },
    {
      label: "Concepts",
      type: "category",
      items: [
        "concept/deduplication",
        "concept/designated-timestamp",
        "concept/geohashes",
        "concept/indexes",
        "concept/interval-scan",
        "concept/jit-compiler",
        "concept/mat-views",
        "concept/partitions",
        "concept/query-tracing",
        {
          customProps: {
            tag: "Enterprise",
          },
          type: "doc",
          id: "concept/replication",
        },
        "concept/root-directory-structure",
        "concept/sql-extensions",
        "concept/sql-optimizer-hints",
        "concept/storage-model",
        "concept/symbol",
        "concept/ttl",
        "concept/write-ahead-log",
      ],
    },
    {
      label: "Third-party Tools",
      type: "category",
      items: [
        {
          type: "doc",
          id: "third-party-tools/overview",
        },
        {
          type: "category",
          label: "Recommended",
          collapsed: false,
          items: [
            "third-party-tools/grafana",
            "third-party-tools/kafka",
            "third-party-tools/redpanda",
            "third-party-tools/powerbi",
            "third-party-tools/pandas",
            "third-party-tools/telegraf",
            "third-party-tools/prometheus",
            "third-party-tools/qstudio",
            "third-party-tools/superset",
            "third-party-tools/flink",
            "third-party-tools/spark",
          ],
        },
        {
          label: "Other tools",
          type: "category",
          collapsed: false,
          items: [
            "third-party-tools/sqlalchemy",
            "third-party-tools/mindsdb",
            "third-party-tools/airflow",
            "third-party-tools/dagster",
            "third-party-tools/cube",
            "third-party-tools/databento",
            "third-party-tools/embeddable",
            "third-party-tools/airbyte",
          ],
        },
      ],
    },
    {
      label: "Troubleshooting",
      type: "category",
      items: [
        "troubleshooting/faq",
        "troubleshooting/os-error-codes",
        "troubleshooting/error-codes",
      ],
    },
  ].filter(Boolean),
}
