module.exports = {
  docs: [
    {
      id: "introduction",
      type: "doc",
    },
    {
      id: "quick-start",
      type: "doc",
      customProps: { tag: "Popular" },
    },
    {
      id: "why-questdb",
      type: "doc",
      customProps: { tag: "Popular" },
    },
    {
      id: "guides/schema-design-essentials",
      type: "doc",
      customProps: { tag: "Popular" },
    },
    {
      type: "category",
      label: "Ingestion Reference",
      items: [
        {
          id: "ingestion-overview",
          type: "doc",
          label: "Overview",
        },
        {
          type: "category",
          label: "Language Clients",
          collapsed: false,
          items: [
            {
              id: "configuration-string",
              type: "doc",
              label: "Configuration string",
            },
            {
              id: "clients/ingest-python",
              type: "doc",
              label: "Python",
            },
            {
              id: "clients/ingest-go",
              type: "doc",
              label: "Go",
            },
            {
              id: "clients/java-ilp",
              type: "doc",
              label: "Java",
            },
            {
              id: "clients/ingest-rust",
              type: "doc",
              label: "Rust",
            },
            {
              id: "clients/ingest-node",
              type: "doc",
              label: "Node.js",
            },
            {
              id: "clients/ingest-c-and-cpp",
              type: "doc",
              label: "C & C++",
            },
            {
              id: "clients/ingest-dotnet",
              type: "doc",
              label: ".NET",
            },
            {
              id: "clients/date-to-timestamp-conversion",
              type: "doc",
              label: "Date to Timestamp Conversion",
            },
          ],
        },
        {
          type: "category",
          label: "Message Brokers",
          collapsed: false,
          items: [
            "third-party-tools/kafka",
            "third-party-tools/telegraf",
            "third-party-tools/redpanda",
            "third-party-tools/flink",
          ],
        },
        {
          type: "category",
          label: "Protocols",
          items: [
            {
              type: "category",
              label: "InfluxDB Line Protocol (ILP)",
              items: [
                "reference/api/ilp/overview",
                "reference/api/ilp/advanced-settings",
                "reference/api/ilp/columnset-types",
              ],
            },
            "reference/api/postgres",
            "reference/api/rest",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Query & SQL Reference",
      items: [
        "reference/sql/overview",
        {
          type: "category",
          label: "PGWire Clients",
          collapsed: false,
          items: [
            {
              id: "pgwire/pgwire-intro",
              type: "doc",
              label: "Overview",
            },
            {
              id: "pgwire/python",
              type: "doc",
              label: "Python",
            },
            {
              id: "pgwire/go",
              type: "doc",
              label: "Go",
            },
            {
              id: "pgwire/java",
              type: "doc",
              label: "Java",
            },
            {
              id: "pgwire/rust",
              type: "doc",
              label: "Rust",
            },
            {
              id: "pgwire/javascript",
              type: "doc",
              label: "Node.js",
            },
            {
              id: "pgwire/c-sharp",
              type: "doc",
              label: ".NET",
            },
            {
              id: "pgwire/php",
              type: "doc",
              label: "PHP",
            },
            {
              id: "pgwire/rpostgres",
              type: "doc",
              label: "R",
            },
            {
              id: "pgwire/c-and-cpp",
              type: "doc",
              label: "C/C++",
            },
          ],
        },
        "reference/sql/datatypes",
        "concept/sql-execution-order",
        {
          type: "category",
          label: "SQL Syntax",
          items: [
            {
              id: "reference/sql/acl/add-user",
              type: "doc",
              customProps: { tag: "Enterprise" },
            },
            {
              type: "category",
              label: "ALTER",
              items: [
                {
                  type: "category",
                  label: "ALTER COLUMN (TABLE)",
                  items: [
                    "reference/sql/alter-table-alter-column-add-index",
                    "reference/sql/alter-table-alter-column-cache",
                    "reference/sql/alter-table-change-column-type",
                    "reference/sql/alter-table-alter-column-drop-index",
                    "reference/sql/alter-table-change-symbol-capacity",
                  ],
                },
                {
                  type: "category",
                  label: "ALTER COLUMN (VIEW)",
                  items: [
                    "reference/sql/alter-mat-view-alter-column-add-index",
                    "reference/sql/alter-mat-view-alter-column-drop-index",
                  ],
                },
                {
                  id: "reference/sql/acl/alter-service-account",
                  type: "doc",
                  customProps: { tag: "Enterprise" },
                },
                {
                  type: "category",
                  label: "ALTER TABLE",
                  items: [
                    "reference/sql/alter-table-add-column",
                    "reference/sql/alter-table-attach-partition",
                    "reference/sql/alter-table-change-column-type",
                    "reference/sql/alter-table-enable-deduplication",
                    "reference/sql/alter-table-disable-deduplication",
                    "reference/sql/alter-table-detach-partition",
                    "reference/sql/alter-table-drop-column",
                    "reference/sql/alter-table-drop-partition",
                    "reference/sql/alter-table-rename-column",
                    "reference/sql/alter-table-resume-wal",
                    "reference/sql/alter-table-set-param",
                    "reference/sql/alter-table-set-ttl",
                    "reference/sql/alter-table-set-type",
                    "reference/sql/alter-table-squash-partitions",
                    "reference/sql/alter-table-change-symbol-capacity",
                  ],
                },
                {
                  type: "category",
                  label: "ALTER MATERIALIZED VIEW",
                  items: [
                    "reference/sql/alter-mat-view-resume-wal",
                    "reference/sql/alter-mat-view-set-refresh",
                    "reference/sql/alter-mat-view-set-refresh-limit",
                    "reference/sql/alter-mat-view-set-ttl",
                    "reference/sql/alter-mat-view-change-symbol-capacity",
                  ],
                },
                {
                  id: "reference/sql/acl/alter-user",
                  type: "doc",
                  customProps: { tag: "Enterprise" },
                },
              ],
            },
            {
              id: "reference/sql/acl/assume-service-account",
              type: "doc",
              customProps: { tag: "Enterprise" },
            },
            "reference/sql/cancel-query",
            "reference/sql/checkpoint",
            "reference/sql/copy",
            {
              type: "category",
              label: "CREATE",
              items: [
                {
                  id: "reference/sql/acl/create-group",
                  type: "doc",
                  customProps: { tag: "Enterprise" },
                },
                "reference/sql/create-mat-view",
                {
                  id: "reference/sql/acl/create-service-account",
                  type: "doc",
                  customProps: { tag: "Enterprise" },
                },
                "reference/sql/create-table",
                {
                  id: "reference/sql/acl/create-user",
                  type: "doc",
                  customProps: { tag: "Enterprise" },
                },
              ],
            },
            {
              type: "category",
              label: "DROP",
              items: [
                {
                  id: "reference/sql/acl/drop-group",
                  type: "doc",
                  customProps: { tag: "Enterprise" },
                },
                "reference/sql/drop-mat-view",
                {
                  id: "reference/sql/acl/drop-service-account",
                  type: "doc",
                  customProps: { tag: "Enterprise" },
                },
                "reference/sql/drop",
                {
                  id: "reference/sql/acl/drop-user",
                  type: "doc",
                  customProps: { tag: "Enterprise" },
                },
              ],
            },
            {
              id: "reference/sql/acl/exit-service-account",
              type: "doc",
              customProps: { tag: "Enterprise" },
            },
            "reference/sql/explain",
            {
              type: "category",
              label: "GRANT",
              items: [
                {
                  id: "reference/sql/acl/grant",
                  type: "doc",
                  customProps: { tag: "Enterprise" },
                },
                {
                  id: "reference/sql/acl/grant-assume-service-account",
                  type: "doc",
                  customProps: { tag: "Enterprise" },
                },
              ],
            },
            "reference/sql/insert",
            "reference/sql/refresh-mat-view",
            "reference/sql/reindex",
            {
              id: "reference/sql/acl/remove-user",
              type: "doc",
              customProps: { tag: "Enterprise" },
            },
            "reference/sql/rename",
            {
              type: "category",
              label: "REVOKE",
              items: [
                {
                  id: "reference/sql/acl/revoke",
                  type: "doc",
                  customProps: { tag: "Enterprise" },
                },
                {
                  id: "reference/sql/acl/revoke-assume-service-account",
                  type: "doc",
                  customProps: { tag: "Enterprise" },
                },
              ],
            },
            {
              type: "category",
              label: "SELECT",
              items: [
                "reference/sql/select",
                "reference/sql/asof-join",
                "reference/sql/case",
                "reference/sql/cast",
                "reference/sql/declare",
                "reference/sql/distinct",
                "reference/sql/fill",
                "reference/sql/group-by",
                "reference/sql/join",
                "reference/sql/window-join",
                "reference/sql/latest-on",
                "reference/sql/limit",
                "reference/sql/order-by",
                "reference/sql/over",
                "reference/sql/sample-by",
                "reference/sql/where",
                "reference/sql/with",
              ],
            },
            "reference/sql/show",
            "reference/sql/snapshot",
            "reference/sql/truncate",
            "reference/sql/union-except-intersect",
            "reference/sql/update",
            "reference/sql/vacuum-table",
          ],
        },
        {
          type: "category",
          label: "Functions",
          items: [
            "reference/function/aggregation",
            "reference/function/array",
            "reference/function/binary",
            "reference/function/boolean",
            "reference/function/conditional",
            "reference/function/date-time",
            "reference/function/finance",
            "reference/function/hash",
            "reference/function/json",
            "reference/function/meta",
            "reference/function/numeric",
            "reference/function/parquet",
            "reference/function/pattern-matching",
            "reference/function/random-value-generator",
            "reference/function/row-generator",
            "reference/function/spatial",
            "reference/function/text",
            "reference/function/timestamp-generator",
            "reference/function/timestamp",
            "reference/function/touch",
            "reference/function/trigonometric",
            "reference/function/uuid",
            "reference/function/window",
          ],
        },
        {
          type: "category",
          label: "Operators",
          items: [
            "reference/operators/bitwise",
            "reference/operators/comparison",
            "reference/operators/date-time",
            "reference/operators/ipv4",
            "reference/operators/logical",
            "reference/operators/misc",
            "reference/operators/numeric",
            "reference/operators/precedence",
            "reference/operators/spatial",
            "reference/operators/text",
          ],
        },
      ],
    },
    {
      label: "Deployment",
      type: "category",
      items: [
        "deployment/docker",
        "deployment/kubernetes",
        "deployment/systemd",
        "deployment/aws",
        "deployment/azure",
        "deployment/gcp",
        "deployment/digital-ocean",
        "deployment/hetzner"
      ],
    },
    {
      label: "Operations",
      type: "category",
      items: [
        {
          id: "operations/migrate-to-enterprise",
          type: "doc",
          customProps: { tag: "Enterprise" },
        },
        "operations/capacity-planning",
        "operations/command-line-options",
        "operations/backup",
        {
          label: "Authentication",
          type: "category",
          collapsed: false,
          items: [
            {
              id: "operations/rbac",
              type: "doc",
              label: "Role-Based Access Control (RBAC)",
              customProps: { tag: "Enterprise" },
            },
            {
              id: "operations/openid-connect-oidc-integration",
              type: "doc",
              label: "OpenID Connect (OIDC)",
              customProps: { tag: "Enterprise" },
            },
            {
              type: "doc",
              id: "operations/tls",
              customProps: { tag: "Enterprise" },
            },
          ],
        },
        "operations/logging-metrics",
        "operations/monitoring-alerting",
        "operations/profiling",
        "operations/data-retention",
        "operations/design-for-performance",
        "operations/updating-data",
        "operations/task-automation",
        {
          type: "doc",
          id: "operations/replication",
          customProps: { tag: "Enterprise" },
        },
        {
          id: "operations/multi-primary-ingestion",
          type: "doc",
          label: "Multi-primary ingestion",
          customProps: { tag: "Enterprise" },
        },
        {
          id: "configuration",
          type: "doc",
        },
      ],
    },
    {
      label: "Guides & Tutorials",
      type: "category",
      items: [
        "guides/create-database",
        "guides/import-csv",
        "guides/mat-views",
        "guides/working-with-timestamps-timezones",
        "guides/compression-zfs",
        {
          id: "guides/enterprise-quick-start",
          type: "doc",
          customProps: { tag: "Enterprise" },
        },
        "guides/export-parquet",
        "guides/replication-tuning",
        "reference/api/java-embedded",
        "guides/modifying-data",
        {
          id: "guides/order-book",
          label: "Order book analytics",
          type: "doc",
        },
        {
          id: "guides/influxdb-migration",
          type: "doc",
          customProps: { tag: "Popular" },
        },
        {
          type: "category",
          label: "Web Console",
          collapsed: true,
          items: [
            "web-console",
            "web-console/code-editor",
            "web-console/metrics-view",
            "web-console/schema-explorer",
            "web-console/result-grid",
            "web-console/query-log",
            "web-console/import-csv",
            "web-console/create-table",
          ],
        },
        {
          label: "Blog tutorials 🔗",
          type: "link",
          href: "https://questdb.com/blog/?tag=tutorial",
        },
      ],
    },
    {
      label: "Concepts",
      type: "category",
      items: [
        "concept/deduplication",
        "concept/designated-timestamp",
        "concept/geohashes",
        "concept/array",
        "concept/decimal",
        "concept/indexes",
        "concept/interval-scan",
        "concept/jit-compiler",
        "concept/mat-views",
        "concept/partitions",
        "concept/query-tracing",
        {
          customProps: {
            tag: "Enterprise",
          },
          type: "doc",
          id: "concept/replication",
        },
        "concept/root-directory-structure",
        "concept/sql-extensions",
        "concept/sql-optimizer-hints",
        "concept/storage-model",
        "concept/symbol",
        "concept/ttl",
        "concept/write-ahead-log",
      ],
    },
    {
      label: "Architecture",
      type: "category",
      items: [
        "guides/architecture/overview",
        "guides/architecture/storage-engine",
        "guides/architecture/memory-management",
        "guides/architecture/query-engine",
        "guides/architecture/time-series-optimizations",
        "guides/architecture/data-ingestion-engine",
        "guides/architecture/networking-layer",
        "guides/architecture/replication-layer",
        "guides/architecture/security",
        "guides/architecture/observability",
        "guides/architecture/web-console",
      ],
    },
    {
      label: "Third-party Tools",
      type: "category",
      items: [
        {
          type: "doc",
          id: "third-party-tools/overview",
        },
        {
          type: "category",
          label: "Recommended",
          collapsed: false,
          items: [
            "third-party-tools/grafana",
            "third-party-tools/kafka",
            "third-party-tools/redpanda",
            "third-party-tools/powerbi",
            "third-party-tools/pandas",
            "third-party-tools/polars",
            "third-party-tools/telegraf",
            "third-party-tools/prometheus",
            "third-party-tools/qstudio",
            "third-party-tools/superset",
            "third-party-tools/flink",
            "third-party-tools/spark",
            "third-party-tools/ignition"
          ],
        },
        {
          label: "Other tools",
          type: "category",
          collapsed: false,
          items: [
            "third-party-tools/sqlalchemy",
            "third-party-tools/mindsdb",
            "third-party-tools/airflow",
            "third-party-tools/dagster",
            "third-party-tools/cube",
            "third-party-tools/databento",
            "third-party-tools/embeddable",
            "third-party-tools/airbyte",
          ],
        },
      ],
    },
    {
      label: "Troubleshooting",
      type: "category",
      items: [
        "troubleshooting/faq",
        "troubleshooting/os-error-codes",
        "troubleshooting/error-codes",
      ],
    },
    {
      label: "Playbook",
      type: "category",
      collapsed: false,
      items: [
        "playbook/overview",
        "playbook/demo-data-schema",
        {
          type: "category",
          label: "SQL Recipes",
          collapsed: true,
          items: [
            {
              type: "category",
              label: "Finance",
              collapsed: true,
              items: [
                "playbook/sql/finance/compound-interest",
                "playbook/sql/finance/cumulative-product",
                "playbook/sql/finance/vwap",
                "playbook/sql/finance/bollinger-bands",
                "playbook/sql/finance/tick-trin",
                "playbook/sql/finance/volume-profile",
                "playbook/sql/finance/volume-spike",
                "playbook/sql/finance/rolling-stddev",
              ],
            },
            {
              type: "category",
              label: "Time-Series Patterns",
              collapsed: true,
              items: [
                "playbook/sql/time-series/force-designated-timestamp",
                "playbook/sql/time-series/latest-n-per-partition",
                "playbook/sql/time-series/session-windows",
                "playbook/sql/time-series/latest-activity-window",
                "playbook/sql/time-series/filter-by-week",
                "playbook/sql/time-series/distribute-discrete-values",
                "playbook/sql/time-series/epoch-timestamps",
                "playbook/sql/time-series/sample-by-interval-bounds",
                "playbook/sql/time-series/remove-outliers",
                "playbook/sql/time-series/fill-from-one-column",
                "playbook/sql/time-series/fill-prev-with-history",
                "playbook/sql/time-series/fill-keyed-arbitrary-interval",
                "playbook/sql/time-series/sparse-sensor-data",
              ],
            },
            {
              type: "category",
              label: "Advanced SQL",
              collapsed: true,
              items: [
                "playbook/sql/advanced/rows-before-after-value-match",
                "playbook/sql/advanced/top-n-plus-others",
                "playbook/sql/advanced/pivot-table",
                "playbook/sql/advanced/unpivot-table",
                "playbook/sql/advanced/sankey-funnel",
                "playbook/sql/advanced/conditional-aggregates",
                "playbook/sql/advanced/general-and-sampled-aggregates",
                "playbook/sql/advanced/consistent-histogram-buckets",
                "playbook/sql/advanced/array-from-string",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Integrations",
          collapsed: true,
          items: [
            "playbook/integrations/opcua-dense-format",
            {
              type: "category",
              label: "Grafana",
              collapsed: true,
              items: [
                "playbook/integrations/grafana/dynamic-table-queries",
                "playbook/integrations/grafana/read-only-user",
                "playbook/integrations/grafana/variable-dropdown",
                "playbook/integrations/grafana/overlay-timeshift",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Programmatic",
          collapsed: true,
          items: [
            "playbook/programmatic/tls-ca-configuration",
            {
              type: "category",
              label: "PHP",
              items: [
                "playbook/programmatic/php/inserting-ilp",
              ],
            },
            {
              type: "category",
              label: "Ruby",
              items: [
                "playbook/programmatic/ruby/inserting-ilp",
              ],
            },
            {
              type: "category",
              label: "C++",
              items: [
                "playbook/programmatic/cpp/missing-columns",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Operations",
          collapsed: true,
          items: [
            "playbook/operations/docker-compose-config",
            "playbook/operations/store-questdb-metrics",
            "playbook/operations/csv-import-milliseconds",
            "playbook/operations/tls-pgbouncer",
            "playbook/operations/copy-data-between-instances",
            "playbook/operations/query-times-histogram",
            "playbook/operations/optimize-many-tables",
            "playbook/operations/check-transaction-applied",
            "playbook/operations/show-non-default-params",
          ],
        },
      ],
    },
    {
      label: "Release Notes",
      type: "link",
      href: "https://questdb.com/release-notes",
    },
  ].filter(Boolean),
}
