name: Preview trigger

on:
  pull_request:
    types: ["opened", "edited", "synchronize"]
  pull_request_target:
    types: [labeled]

jobs:
  pr-preview:
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) ||
      (github.event_name == 'pull_request_target' && github.event.label.name == 'preview')
    name: "PR preview"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout questdb.com repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Build site
        env:
          CONTEXT: deploy-preview
          NETLIFY: true
        run: yarn build

      - name: Deploy to Netlify
        id: netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          PREVIEW_URL=$(netlify deploy \
            --dir=build \
            --no-build \
            --auth=$NETLIFY_AUTH_TOKEN \
            --site=$NETLIFY_SITE_ID \
            --alias=preview-${{ github.event.pull_request.number }} \
            --message="Preview Deploy from GitHub Actions" \
            --json | jq -r '.deploy_url')
          echo "NETLIFY_PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV

      - name: "Update PR"
        if: env.NETLIFY_PREVIEW_URL
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :rocket: **Build success!**

            Latest successful preview: ${{ env.NETLIFY_PREVIEW_URL }}

            Commit SHA: ${{ github.event.pull_request.head.sha }}

            > :package: Build generates a preview & updates link on each commit.
          comment_tag: preview

  validate-links:
    name: "Validate broken links"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build site for broken link validation
        run: |
          yarn build
