name: Preview trigger

on:
  pull_request:
    types: ["opened", "edited", "synchronize"]

jobs:
  pr-preview:
    name: "PR preview"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout questdb.io repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build site
        env:
          CONTEXT: deploy-preview
          NETLIFY: true
        run: yarn build

      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: build
          install_command: "echo Skipping installing the dependencies"
          build_command: "echo Skipping building the web files"
          deploy_alias: preview-${{ github.event.pull_request.number }}

      - name: "Update PR"
        if: ${{ env.NETLIFY_PREVIEW_URL }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :rocket: **Build success!**

            Latest successful preview: ${{ env.NETLIFY_PREVIEW_URL }}

            Commit SHA: ${{ github.event.pull_request.head.sha }}

            > :package: Build generates a preview & updates link on each commit.

          comment_tag: execution